name: CI

on: [push, pull_request]

jobs:
  ci:
    uses: lalalili/.github/.github/workflows/php-package-ci.yml@main
    secrets: inherit
    with:
      php-versions: "['8.4']"
      php-extensions: 'dom, mbstring, pdo_sqlite, sockets, zip'
      run-browser: true
      run-validate: false
